#
# Your Crowdin credentials
#
"project_id_env" : "CROWDIN_PROJECT_ID"
"api_token_env" : "CROWDIN_PERSONAL_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

#
# Choose file structure in Crowdin
# e.g. true or false
#
"preserve_hierarchy": true
#
# Files configuration
#
files: [
  {
    "source": "/agenda-webapps/src/main/resources/locale/commons/Commons_en.properties",

    "translation": "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest": "add__ons/agenda/Commons.properties",
    "update_option": "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes": 0,
  },
  {
    "source" : "/agenda-webapps/src/main/resources/locale/navigation/portal/global_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/agenda/global.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/agenda-webapps/src/main/resources/locale/portal/webui_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/agenda/webui.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/agenda-webapps/src/main/resources/locale/portlet/Agenda_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/agenda/Agenda.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/agenda-webapps/src/main/resources/locale/portlet/Portlets_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/agenda/Portlets.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/agenda-webapps/src/main/resources/locale/notification/AgendaNotification_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/agenda/AgendaNotification.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/agenda-webapps/src/main/resources/locale/portlet/Analytics_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/agenda/Analytics.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/agenda-webapps/src/main/resources/locale/addon/Gamification_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/agenda/Gamification.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/agenda-webapps/src/main/resources/locale/portlet/LayoutEditor_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/agenda/LayoutEditor.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source" : "/agenda-webapps/src/main/resources/locale/portlet/ContentLink_en.properties",

    "translation" : "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace" : {YML_CROWDIN_LANGUAGES_ARG},
    "dest" : "add__ons/agenda/ContentLink.properties",
    "update_option" : "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes" : 0,
  },
  {
    "source": "/agenda-webapps/src/main/resources/locale/portlet/ContentExtension_en.properties",

    "translation": "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace": { YML_CROWDIN_LANGUAGES_ARG },
    "dest": "add__ons/agenda/ContentExtension.properties",
    "update_option": "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes": 0,
  },
  {
    "source": "/agenda-webapps/src/main/resources/locale/portlet/StreamExtension_en.properties",

    "translation": "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace": { YML_CROWDIN_LANGUAGES_ARG },
    "dest": "add__ons/agenda/StreamExtension.properties",
    "update_option": "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes": 0,
  },
  {
    "source": "/agenda-webapps/src/main/resources/locale/portlet/ContentEditorExtension_en.properties",

    "translation": "%original_path%/%file_name%!_%locale_with_underscore%.%file_extension%",
    "translation_replace": { YML_CROWDIN_LANGUAGES_ARG },
    "dest": "add__ons/agenda/ContentEditorExtension.properties",
    "update_option": "update_as_unapproved",
    "escape_special_characters": 0,
    "escape_quotes": 0,
  },
]
