// SPDX-FileCopyrightText: 2021 eXo Platform SAS
//
// SPDX-License-Identifier: AGPL-3.0-only

package org.exoplatform.agenda.constant;

public enum AgendaEventModificationType {
  ADDED,
  UPDATED,
  DELETED,
  RECURRENCE_DELETED,
  SWITCHED_EVENT_TO_DATE_POLL,
  SWITCHED_DATE_POLL_TO_EVENT,
  DATE_OPTION_SELECTED,
  DATE_OPTION_UPDATED,
  DATE_OPTION_CREATED,
  DATE_OPTION_DELETED,
  SUMMARY_UPDATED,
  DESCRIPTION_UPDATED,
  OWNER_UPDATED,
  DATES_UPDATED,
  START_DATE_UPDATED,
  END_DATE_UPDATED,
  LOCATION_UPDATED,
  COLOR_UPDATED,
  TIMEZONE_UPDATED,
  AVAILABILITY_UPDATED,
  STATUS_UPDATED,
  RECURRENCE_UPDATED,
  ATTENDEE_ADDED,
  ATTENDEE_DELETED,
  CONFERENCE_ADDED,
  CONFERENCE_DELETED,
  REMINDER_ADDED,
  REMINDER_DELETED,
  ALLOW_INVITE_UPDATED,
  ALLOW_MODIFY_UPDATED,
}
